[Sapling] Incremental merkle tree backport.
PIVX-Project/PIVX pull request #1870
Opened 2020-09-25 05:15 UTC by furszy

This is coming from #1798, focused on include the incremental merkle tree primitive with all of its unit tests.
This base primitive class is almost one to one with upstream.

Decoupled the following commits:

* Incremental Merkle Tree + merkletree tests back port —> 762d5f10
* Rename sapling util file to not shadow src/util file --> cae89d3b

2020-09-28 19:56 UTC, furszy commented
This is fixing #1798 travis issues. took a while to decouple it but it's is ready for review.

2020-10-01 18:21 UTC, Fuzzbawls requested changes
Could use some cleanup regarding our own standards and helpers/wrappers so as to not re-introduce new boost dependencies.

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +
`#include optional.h` to have our own wrapper available for calls below

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +        boost::optional<Hash> combined = Hash::combine(*left, *right, 0);
`Optional<Hash>...`

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +    BOOST_FOREACH(const boost::optional<Hash>& parent, parents) {
`Optional<Hash>&`

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +    BOOST_FOREACH(const boost::optional<Hash>& parent, parents) {
Optional<Hash>&

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +    BOOST_FOREACH(const boost::optional<Hash>& parent, parents) {
Optional<Hash>&

2020-10-01 18:21 UTC, Fuzzbawls commented on src/sapling/incrementalmerkletree.cpp
> +    BOOST_FOREACH(const boost::optional<Hash>& parent, parents) {
Optional<Hash>&

2020-10-01 21:07 UTC, furszy commented
Done, styling updated to our sources conventions 👍 .

2020-10-03 11:44 UTC, random-zebra approved these changes
ACK 626b0d93a3eef3abd3f481779ea507919b3eacb5

2020-10-03 19:55 UTC, Fuzzbawls approved these changes
utACK 626b0d93a3eef3abd3f481779ea507919b3eacb5

2020-10-03 20:15 UTC, merged