[Validation] v8 blocks, Sapling merkle tree inclusion.
PIVX-Project/PIVX pull request #1910
Opened 2020-10-10 21:24 UTC by furszy

Another decoupling from #1798, built on top of #1903 .

Containing three topics:

1) Sapling merkle tree root hash inclusion in the block header.
   * Block version bumped to v8.
   * Miner crafting the new merkle tree root hash and setting it into the block.

2) Track network total value entering and exiting the shielded pool. (*)
   * Similar to the previous, initial, zc failsafe flow. (this can be done much better, like we did with zerocoin supply)
   * Block negative shielded value pool balances. -- Network validation consensus rule --

3) ChainTip signal implemented.
   * Signal to notify the listeners (wallet) about new blocks (or chain reorgs), broadcasting the new block and the current merkle tree so the listener can build upon it.

#### This PR is including the following commits decoupled from #1798.

* Track net value entering and exiting the Sapling circuit.—> 8dd2045034b146d68eb6ef592433348852d54edd
* Block: header hashFinalSaplingRoot inclusion.—> 5f55a76bd303e21ed31e1947eb12d44a999f667f
* Sapling: missing nSaplingValue in LoadBlockIndexGuts added.—> fbe07613cf296ccc3f0a1b55f0015e86e2ff3d39
* Miner: sapling tree hash connection.—> cb88fae28eaa760c7feb00ab5ccd6f1cb8e6db15
* Implement ChainTip signal. —> 4e96e6c97d258c87910d2e9ab13cbb79c25ebda5
* Signal ChainTip in ConnectTip and DisconnectTip methods —> 85f4435b4076c8d4c8e222a0e0d7b8f76465be63
* Pass chainparams as argument in DisconnectTip, InvalidateBlock, ReprocessBlocks, DisconnectBlocks, DisconnectTip —> 1c809536b862e59554dc9ebee8651c56935a0f9a
* Do not try to update tree anchor and witnesses if sapling is not active --> 1c64497d4f020d6c400c7aa836f75dce7d1517d4
* Validation: Adapted the cached incremental witnesses update flow to the syncTransaction changes. —> 6e6372df9270dba2f76836d5b964c2153e28bda6

2020-10-14 05:00 UTC, furszy commented
rebased this on top of #1915, making it depend on it.
The reason is that #1915 makes `ChainTip` signal flow much performant with cleaner code.

2020-10-20 05:56 UTC, Fuzzbawls reviewed
Some consistency comments left about using our `optional.h` wrapper around `boost::optional`, but otherwise looking good

2020-10-20 05:56 UTC, Fuzzbawls commented on src/chain.h
> +    boost::optional<CAmount> nChainSaplingValue{boost::none};
If you include our `optional.h` header, can use our wrapper template and substitute
```cpp
Optional<CAmount> nChainSaplingValue{nullopt};
```

2020-10-20 05:56 UTC, Fuzzbawls commented on src/rpc/blockchain.cpp
> +        const boost::optional<CAmount> valueDelta)
Same here, include `optional.h` and use `Optional<CAmount> ...`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validation.cpp
> +        GetMainSignals().ChainTip(pindexDelete, &block, boost::none);
`nullopt` instead of `boost::none`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validation.cpp
> +                    pindex->nChainSaplingValue = boost::none;
`nullopt` instead of `boost::none`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validation.cpp
> +                        pindex->nChainSaplingValue = boost::none;
`nullopt` instead of `boost::none`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validation.cpp
> +                    pindex->nChainSaplingValue = boost::none;
`nullopt` instead of `boost::none`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validationinterface.h
> +#include "sapling/incrementalmerkletree.hpp"
should be above the 3rd party lib includes

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validationinterface.h
> +    virtual void ChainTip(const CBlockIndex *pindex, const CBlock *pblock, boost::optional<SaplingMerkleTree> added) {}
include `optional.h` and use `Optional<>` instead of `boost::optional<>`

2020-10-20 05:56 UTC, Fuzzbawls commented on src/validationinterface.h
> +    boost::signals2::signal<void (const CBlockIndex *, const CBlock *, boost::optional<SaplingMerkleTree>)> ChainTip;
include `optional.h` and use `Optional<>` instead of `boost::optional<>`

2020-10-20 14:01 UTC, random-zebra requested changes
There's an issue with the new RPC fields implementation (UniValue object elements must be a pair key-object, not plain objects).

Aside from this, we should consider if we really want to store in memory `nChainSaplingValue` for all blocks. That would add more than 20 MB to the runtime memory consumption at the current chain size (on mainnet). 
Not so much... but still, we only need its value at the chain tip.
Probably fine to leave it as is in this PR, but  something we might want to consider later.

2020-10-20 19:38 UTC, furszy commented on src/rpc/blockchain.cpp
> +        rv.pushKV("chainValueZat", *chainValue);
yeah, done.
Plus, removed the `monitored` boolean as well.

2020-10-20 19:52 UTC, furszy commented on src/rpc/blockchain.cpp
> +    result.pushKV("finalsaplingroot", block.hashFinalSaplingRoot.GetHex());
doing it. 
Curious thing, we never documented the accumulator checkpoint in `getblock`.

2020-10-20 19:58 UTC, furszy commented on src/rpc/blockchain.cpp
> +    result.pushKV("finalsaplingroot", block.hashFinalSaplingRoot.GetHex());
And for the release notes, better to leave them for when all of the Sapling work gets merged.

All of the `Sapling` tagged PRs will need them. Up until now, haven't added anything to the release notes and we have merged several new features, RPC commands and consensus changes in master. So.. better to continue moving and do it all at once properly at the end.

2020-10-20 20:01 UTC, furszy commented on src/validation.cpp
> +    const CChainParams& chainparams = Params();
yeah, can squash them now. 
At the beginning the flow was totally different, #1915 made this quite nicer.

2020-10-20 20:03 UTC, furszy commented
Updated per feedback.

2020-10-22 14:24 UTC, random-zebra approved these changes
Just a minor nit for the help output.
Otherwise ACK.

2020-10-22 14:24 UTC, random-zebra commented on src/rpc/blockchain.cpp
> +            "     \"valueDelta\":        (bool) Change in value held by the Sapling circuit over this block\n"
(e971fccc144386e16be0cc7ebf2ecbfcab0dc5e8)
numeric, not bool. Value expressed in PIV.

2020-10-22 14:24 UTC, random-zebra commented on src/rpc/blockchain.cpp
> +            "     \"valueDelta\":        (bool) Change in value held by the Sapling circuit over the chain tip block\n"
(e971fccc144386e16be0cc7ebf2ecbfcab0dc5e8)
same

2020-10-22 14:38 UTC, furszy commented
Done, updated per feedback.

2020-10-22 14:41 UTC, random-zebra approved these changes
utACK 140391871c0a0b08d1e38cde464470ec71b6dddd

2020-10-23 02:52 UTC, Fuzzbawls approved these changes
utACK 140391871c0a0b08d1e38cde464470ec71b6dddd

2020-10-23 03:03 UTC, merged