CMasternode::GetLastPaid cleaning another strange piece of "code"
PIVX-Project/PIVX pull request #1939
Opened 2020-10-23 15:42 UTC by furszy

`CMasternode::GetLastPaid`, instead of using the chain tip index, and loop backwards to **only** obtain the block height, use the cached height.

2020-10-26 21:19 UTC, random-zebra requested changes
This doesn't  look right.
The `nBlockHeight`argument of `CMasternodeMan::GetNextMasternodeInQueueForPayment`, that here is passed to `CMasternode::SecondsSincePayment`, is not necessarily the chain height. 
In fact, most of the times it isn't, it could even be **higher** (as we use it to get the hash at `height - 101`)... e.g. see the call to `masternodePayments.ProcessBlock` in validation.cpp).

In `CMasternode::GetLastPaid()`, instead, we want to start exactly at the tip, and go backwards, to find the block where a particular masternode was paid.
I think that a better approach would be to move this function to the manager, returning the height only (e.g. `int CMasternodeMan::GetBlockLastPaid(const CTxIn& mnode_vin)`).
Then access the chainActive, and get the time, outside of it, without any other lock held.
Of course this would require to implement something like `int64_t CMasternode::GetOffset()` too.

2020-10-26 21:19 UTC, random-zebra commented on src/masternode.h
> +    int64_t SecondsSincePayment(int nChainHeight);
```suggestion
    int64_t SecondsSincePayment(int nChainHeight) const;
```

2020-10-26 21:19 UTC, random-zebra commented on src/masternode.h
> +    int64_t GetLastPaid(int nChainHeight);
```suggestion
    int64_t GetLastPaid(int nChainHeight) const;
```

2020-11-16 20:01 UTC, furszy commented
Good point, will rework it differently.

2020-12-16 22:38 UTC, closed without merging