[GUI][Trivial] Expand checkbox column to show 3 digit amount of UTXOs
PIVX-Project/PIVX pull request #2033
Opened 2020-12-05 21:49 UTC by NoobieDev12

For example, if user is running a masternode, after 100+ days of receiving rewards and not moving them, there will be more than 100 different UTXOs. Default column width when starting a wallet is currently not wide enough to show 3 digit amount of UTXOs. This PR fixes it.

**Before:**
![before01](https://user-images.githubusercontent.com/57232689/101265971-61ee1580-374b-11eb-9874-b4cd791bcad2.JPG)

**After:**
![After01](https://user-images.githubusercontent.com/57232689/101265975-64e90600-374b-11eb-9b24-e5034d3c418a.JPG)

2020-12-06 10:52 UTC, Fuzzbawls requested changes
Concept ACK. On my particular system however, a value of `90` was not quite enough to achieve the desired result. Suggest you test with `96-100` to cover differences in pixel ratios across every platform (for reference, `95` was the absolute minimum that worked for me, though it looked rather tight).

I personally would prefer to see a bit too much padding, than not enough...so maybe err closer towards `100` just to be safe.

This is what `100` looks like for me:
![ScreenShot_20201206025153](https://user-images.githubusercontent.com/7393257/101278125-1bf67900-376e-11eb-8d40-776d8b5c4b5c.png)

2020-12-06 14:11 UTC, NoobieDev12 commented
Thank for the feedback Fuzzbawls!

Besides that, I added more changes that looks the most natural to me (Date is being fully showed now).

**Before:**
![before1](https://user-images.githubusercontent.com/57232689/101282381-25ff9280-37d5-11eb-8cfb-58d062ca9b0c.JPG)

**After:**
![after1](https://user-images.githubusercontent.com/57232689/101282386-2ac44680-37d5-11eb-8a04-e2e84449f24c.JPG)

2020-12-07 08:45 UTC, Fuzzbawls commented
I've squashed this down to 1 commit and updated the title

2020-12-07 08:45 UTC, Fuzzbawls approved these changes
ACK 1b7317cfcd921b2c97c69587cfed2c8dd938e2e7

2020-12-07 09:30 UTC, random-zebra approved these changes
ACK 1b7317cfcd921b2c97c69587cfed2c8dd938e2e7, with a non-blocking comment.

The confirmations are visible only in tree-mode.
Setting a wider column by default leaves a big chunk of white space in list-mode (between the checkbox and the address), so it would be better to adjust the width, programmatically, when switching between tree and list modes.

2020-12-16 22:33 UTC, furszy approved these changes
utACK 1b7317c, good first contribution :)

2020-12-16 22:46 UTC, merged