Guarding wallet access from init and print error for unknown MN collaterals
PIVX-Project/PIVX pull request #2218
Opened 2021-02-26 21:11 UTC by furszy

Two changes:

1) Guarding `pwalletMain` access from init.cpp, so in the future we could enable pivxd to run without the wallet.
2) BugFix: `Wallet::LockCoin` verifying that the MN collateral utxo is in the wallet's map before add it to the locked set. Printing the correct error if the transaction is unknown for the wallet.

2021-02-27 09:22 UTC, Fuzzbawls submitted a review, later dismissed
ACK fbe9200de99ad0b4847eea2c9c8b6af5191bc42f

2021-02-27 10:53 UTC, Fuzzbawls commented
needs rebase now

2021-02-27 12:32 UTC, random-zebra requested changes
The second commit introduces a subtle risk.
With this change, if a controller's wallet is zapped, and then reindexes/resyncs, then the masternode collaterals are not locked during init.
Thus they could be inadvertently spent, when the reindex completes.

A similar (but less likely) situation can happen in this case:
1) Create a new controller from scratch. Before it completes the sync, get a receiving address.
2) From another client, send the collateral to the receiving address created in (1), and get the txid
3) Add the txid to the masternode.conf of the controller (which still hasn't completed the sync, nor added the tx to his wallet) and restart it.
4) When the sync completes, the masternode owner could think that the collateral is locked, but it isn't.

2021-02-27 14:09 UTC, furszy commented
good points.
Will modify the second commit to not block the output append, have thought on some ways to cover the presented scenarios but it simply doesn't worthy it as it would add an extra overhead during sync/rescan processes for such a small benefit.

2021-02-27 14:15 UTC, random-zebra commented
Agreed.
Further, DMNs will remove the masternode.conf file and locking will be automatic, so there is no need to overthink this.

2021-02-27 14:17 UTC, furszy commented
pushed + rebased on master.

2021-02-27 14:23 UTC, random-zebra approved these changes
utACK de6f052616e6b52fd886bd235648187f2fd110d4

2021-02-28 11:31 UTC, Fuzzbawls approved these changes
re-ACK de6f052616e6b52fd886bd235648187f2fd110d4

2021-02-28 13:14 UTC, merged