[RPC][wallet] Add `rescanblockchain` RPC command functionality
PIVX-Project/PIVX pull request #2240
Opened 2021-03-10 14:22 UTC by furszy

Added the following changes:

1) The wallet scan chain for transactions process will now return null if scan was successful. Otherwise, if a complete rescan was not possible (due to corruption or abort), returns pointer to the most recent block that could not be scanned.
2) New `rescanblockchain` RPC command with two arguments `start_height` `end_height` to trigger a chain rescan at any time during runtime + test case (adaptation of #7061).
3) New `abortrescan` RPC command to stop any long running rescan if needed at runtime (this is helpful for example in case of importing a private/sapling key that if the user is not aware of the extra "scan" boolean argument, it will rescan the complete chain). Coming from #10208.

2021-03-10 22:23 UTC, Fuzzbawls requested changes
some initial styling changes left. also, prefer to have a blank line before the `Arguments:`, `Result:`, and `Examples:` sections for readability.

2021-03-10 22:23 UTC, Fuzzbawls commented on src/wallet/rpcwallet.cpp
> +                "rescanblockchain (\"start_height\") (\"stop_height\")\n"
no quotes around numeric arguments

2021-03-10 22:23 UTC, Fuzzbawls commented on src/wallet/rpcwallet.cpp
> +                "2. \"stop_height\"     (numeric, optional) the last block height that should be scanned\n"
no quotes around numeric arguments

2021-03-10 22:23 UTC, Fuzzbawls commented on src/wallet/rpcwallet.cpp
> +                "  \"stop_height\"      (numeric) The height of the last rescanned block. If omitted, rescan stopped at the chain tip.\n"
```cpp
                "  \"start_height\": n,     (numeric) The block height where the rescan has started. If omitted, rescan started from the genesis block.\n"
                "  \"stop_height\": n      (numeric) The height of the last rescanned block. If omitted, rescan stopped at the chain tip.\n"
```

2021-03-10 22:50 UTC, furszy commented on src/wallet/rpcwallet.cpp
> +                "rescanblockchain (\"start_height\") (\"stop_height\")\n"
updated

2021-03-10 22:51 UTC, furszy commented
updated per feedback, removed the quotes around numeric arguments.

2021-03-30 00:03 UTC, random-zebra approved these changes
ACK 896520ed6a2637b6a734d1faf3f9f2dc780252af

This needs a bit more work to be usable from the GUI console, due to the `cs_main` lock, which is held for the whole duration (essentially we need to get to bitcoin#11281... the rabbit hole starts with #2277).
Other than that, this works as intended from a headless node.

2021-04-04 00:05 UTC, Fuzzbawls approved these changes
ACK 896520ed6a2637b6a734d1faf3f9f2dc780252af

2021-04-04 07:01 UTC, merged