[wallet] Remove now unneeded stake P2PKH->P2PK output forced conversion
PIVX-Project/PIVX pull request #2299
Opened 2021-04-08 00:19 UTC by furszy

Since v5 activation, #1700 is active and there is no need to continue checking for the v5 NU enforcement during the coinstake generation in the mining process. This PR removes the extra validations and script conversion inside the wallet.

2021-04-08 12:59 UTC, random-zebra requested changes
This is not taking into account regtest net.
v5 network upgrade is not active by default there.
If we remove the conversion to P2PK inputs, the block validity checks will fail before v5 NU enforcement.

We first need to relax the rules about the block signature (always accepting P2PKH coinstake outs), which is done inside #2295.
With that change, all the tests would be passing here.

So, imo either rebase this PR on top of #2295, or simply add these 3 commits there.

2021-04-08 14:03 UTC, furszy commented
Yeah, i did this one with my head on #2295.
Which needs to get merged first so we can have all the tests passing here.

2021-04-10 13:59 UTC, random-zebra approved these changes
utACK 12648c6af92c0ce62d96a55b27e805783171debc

2021-04-24 11:05 UTC, furszy commented
Done, rebased on master.

2021-04-24 16:58 UTC, random-zebra approved these changes
re-utACK 50ee79d5ac4a29d3d4cc0c4ab780c2df069dc55f after rebase

2021-05-01 09:43 UTC, Fuzzbawls approved these changes
utACK 50ee79d5ac4a29d3d4cc0c4ab780c2df069dc55f

2021-05-01 11:51 UTC, merged