[Doc] v5.1.0 Release Notes
PIVX-Project/PIVX pull request #2333
Opened 2021-04-22 13:59 UTC by furszy

Finalized release notes for v5.1.0

TO DO:
Add #2327 and #2321 when they are merged in the 5.1 branch.

2021-04-23 11:31 UTC, random-zebra requested changes
Looks like the script pulled a bunch of PRs that were part of the previous releases. 
Not sure if I got them all.

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2137 Fix superblock block value (random-zebra)
All these were part of either 5.0.0 or 5.0.1

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2067 Reject outdated block version after v5 enforcement (random-zebra)
part of 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2052 [Miner] Update block header's current version to v8 (Fuzzbawls)
part of 5.0.0. 
2243 supersedes it in 5.1.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2054 Socks5 netbase back ports, less scary failures (furszy)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2045 [TierTwo] Remove unneeded extra logging (furszy)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2108 Set DEFAULT_SHIELDEDTXFEE_K to 100 (from 1000) (random-zebra)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2109 clear StakeableCoins before initializing (PeterL73)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2120 Update Sapling HD chain seed with sethdseed (random-zebra)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2047 [BUG][RPC] Fix check in wallet upgrade RPC (random-zebra)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2128 Receive screen, fix missing "Add label" text (furszy)
Either in 5.0.0 or 5.0.1 already

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2123 Attempt to fix the diversified address equal to default address test scenario (furszy)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2087 Unify header file extensions (Fuzzbawls)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2083 [Core] Prevector Optimizations (random-zebra)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2103 [Startup] Do not block local peer port selection for Masternodes running over tor (furszy)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2114 v5 Release Notes (furszy)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2121 Save cold-staking address in contacts (random-zebra)
in 5.0.0

2021-04-23 11:31 UTC, random-zebra commented on doc/release-notes.md
> +- #2058 [Cleanup] Removing unused DisconnectBlocks and ReprocessBlocks (furszy)
in 5.0.0

2021-04-23 19:50 UTC, furszy commented
ok done, thanks for the feedback. Need to tweak this new script a bit more.
Went through all the lines one by one manually, should be fine now.

2021-04-23 21:10 UTC, random-zebra approved these changes
utACK 925e74f1c0d05aa75ce856e4d1e9413bd3aaab51

2021-04-24 04:34 UTC, Fuzzbawls reviewed
The first two lines of the file should be removed, and instances of `*version*` replaced with the version (ie `v5.1.0`) (line 3 and the inline comment location).

Also this above the `How to Upgrade` section:
```
Recommended Update
==============

This version is an optional, but recommended, update for all users and services.
```

Otherwise good to go

2021-04-24 04:34 UTC, Fuzzbawls commented on doc/release-notes.md
>  *version* Change log
`*version*` -> `v5.1.0`

2021-04-24 10:51 UTC, furszy commented on doc/release-notes.md
>  *version* Change log
done

2021-04-24 10:52 UTC, furszy commented
Updated per feedback.

2021-04-24 11:34 UTC, random-zebra approved these changes
re-utACK 8993dd122ba3c89688b4533a8a9bc24eca8c4a3a

2021-04-24 11:44 UTC, furszy commented
Merging and tagging.. 🚜

2021-04-24 12:43 UTC, merged