[Core][Build] Fix atomic data races in BLS operations
PIVX-Project/PIVX pull request #2702
Opened 2021-12-28 11:32 UTC by Fuzzbawls

Coming from https://github.com/dashpay/dash/pull/4240, https://github.com/bitcoin/bitcoin/pull/20938, and https://github.com/bitcoin/bitcoin/pull/21920, this resolves numerous compile-time inconsistencies/failures on certain combos of gcc and cpu arch that were observed on launchpad.net over the 5.4.0 release cycle.

2022-01-06 11:44 UTC, Fuzzbawls commented
Example of failing build log: [launchpad.net nightly PPA, Ubuntu 16.04 ARM64](https://launchpadlibrarian.net/578674233/buildlog_ubuntu-xenial-arm64.pivx_5.3.99~202201051832+git017953ee0~ubuntu16.04.1_BUILDING.txt.gz)

2022-01-07 19:55 UTC, furszy requested changes
Code reviewed a2af7d9e
~There is an undefined behavior on Dash backported PR.~

Update: Never mind.., `enable_shared_from_this` is protecting this from happening.

2022-01-07 20:25 UTC, furszy commented on src/bls/bls_worker.cpp
> +            auto self(this->shared_from_this());
nvm for this, `enable_shared_from_this` is protecting this from happening.

2022-01-08 12:59 UTC, Fuzzbawls commented
Feedback tackled and rebased on current master

2022-01-08 14:30 UTC, furszy approved these changes
ACK c76e7b6fa4d8452657f60569aaf8dff4fa0d0083

2022-01-09 09:56 UTC, random-zebra approved these changes
ACK c76e7b6fa4d8452657f60569aaf8dff4fa0d0083

2022-01-09 10:51 UTC, merged