[GUI] Decouple legacy MNs code from the GUI elements
PIVX-Project/PIVX pull request #2721
Opened 2022-01-14 00:53 UTC by furszy

Encapsulating the legacy Masternodes code that is spread over the GUI widgets inside the MN module.

Part of the building blocks for adding visual support for the new deterministic Masternodes features.

2022-01-17 18:01 UTC, furszy commented
Ended up moving the collateral min conf value to `chainparams` here (to not have to create another small PR for it and rebase all the other branches on top of it).
This is one of the few shared values between legacy and deterministic Masternodes. Which not only allowed me to finish this encapsulation work, it removed the following circular dependency as well: "evo/deterministicmns -> masternode -> wallet/wallet -> evo/deterministicmns"

2022-01-18 11:31 UTC, random-zebra submitted a review, later dismissed
ACK e364c34456959cc861bfec1ceda1d653af8019da. Just few nits

2022-01-18 12:53 UTC, furszy commented on src/qt/pivx/masternodewizarddialog.cpp
> +        QString errorStr;
because i was thinking on a different upper flow while was doing this.. corrected.

2022-01-18 12:54 UTC, furszy commented
updated per feedback, nits tackled

2022-01-18 13:00 UTC, random-zebra submitted a review, later dismissed
force-push utACK c42547e7992778a2f304257c359528db08431422

2022-01-29 07:44 UTC, Fuzzbawls approved these changes
ACK c42547e7992778a2f304257c359528db08431422

2022-01-29 12:29 UTC, furszy commented
rebased, conflicts solved.

2022-01-29 14:32 UTC, random-zebra requested changes
found a little bug.

2022-01-29 14:32 UTC, random-zebra commented on src/qt/pivx/masternodeswidget.cpp
> +    int success_amount;
uninitialized variables lead to UB.

2022-01-29 16:19 UTC, furszy commented on src/qt/pivx/masternodeswidget.cpp
> +    int success_amount;
fixed

2022-01-31 07:42 UTC, Fuzzbawls approved these changes
re-ACK 18e270de1741f6e83aae55b201c392b0397752e8

2022-01-31 07:58 UTC, merged