[Consensus] New block rewards - preliminary PR for review
PIVX-Project/PIVX pull request #2763
Opened 2022-07-06 23:08 UTC by tohsnoom

Adjust block rewards for staking, masternode and budget to change to new values when V5.5 upgrade block is reached.

Adds UPGRADE_V5.5 block height value to chainparams, currently set to placeholder values for mainnet and testnet.

Adds nNewMNBlockReward value to chainparams--note the planned refactoring to call Params().GetConsensus().nMNBlockReward directly would need to be rethought or wait until after change has taken effect since there are now two parameters which is selected in GetMasternodePayment.

Unit tests for these changes are still WIP.

2022-07-12 20:02 UTC, Fuzzbawls commented
some additional changes to address the issues with the regression test suite:
```diff
Index: test/functional/test_framework/test_framework.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/functional/test_framework/test_framework.py b/test/functional/test_framework/test_framework.py
--- a/test/functional/test_framework/test_framework.py	(revision fe1c0adfaff413b7ce03793e8d012e0334dab0d7)
+++ b/test/functional/test_framework/test_framework.py	(date 1657598250506)
@@ -1630,7 +1630,7 @@
         self.minerPos = 4
         self.remoteDMN1Pos = 5
 
-        self.extra_args = [["-nuparams=v5_shield:249", "-nuparams=v6_evo:250", "-whitelist=127.0.0.1"]] * self.num_nodes
+        self.extra_args = [["-nuparams=v5_shield:249", "-nuparams=PIVX_v5.5:250", "-nuparams=v6_evo:250", "-whitelist=127.0.0.1"]] * self.num_nodes
         for i in [self.remoteOnePos, self.remoteTwoPos, self.remoteDMN1Pos]:
             self.extra_args[i] += ["-listen", "-externalip=127.0.0.1"]
         self.extra_args[self.minerPos].append("-sporkkey=932HEevBSujW2ud7RfB1YF91AFygbBRQj3de3LyaCRqNzKKgWXi")
Index: src/consensus/upgrades.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/consensus/upgrades.cpp b/src/consensus/upgrades.cpp
--- a/src/consensus/upgrades.cpp	(revision fe1c0adfaff413b7ce03793e8d012e0334dab0d7)
+++ b/src/consensus/upgrades.cpp	(date 1657591085736)
@@ -62,6 +62,10 @@
                 /*.strInfo =*/ "New staking rules",
         },
         {
+                /*.strName =*/ "PIVX_v5.5",
+                /*.strInfo =*/ "New rewards structure",
+        },
+        {
                 /*.strName =*/ "v6_evo",
                 /*.strInfo =*/ "Deterministic Masternodes",
         },
Index: test/functional/tiertwo_dkg_errors.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/functional/tiertwo_dkg_errors.py b/test/functional/tiertwo_dkg_errors.py
--- a/test/functional/tiertwo_dkg_errors.py	(revision fe1c0adfaff413b7ce03793e8d012e0334dab0d7)
+++ b/test/functional/tiertwo_dkg_errors.py	(date 1657597464929)
@@ -15,7 +15,7 @@
 
     def set_test_params(self):
         self.set_base_test_params()
-        self.extra_args = [["-nuparams=v5_shield:1", "-nuparams=v6_evo:130", "-debug=llmq", "-debug=dkg", "-debug=net"]] * self.num_nodes
+        self.extra_args = [["-nuparams=v5_shield:1", "-nuparams=PIVX_v5.5:130", "-nuparams=v6_evo:130", "-debug=llmq", "-debug=dkg", "-debug=net"]] * self.num_nodes
         self.extra_args[0].append("-sporkkey=932HEevBSujW2ud7RfB1YF91AFygbBRQj3de3LyaCRqNzKKgWXi")
 
     def reset_simerror(self, node):
```

2022-07-30 07:05 UTC, Fuzzbawls requested changes
After some more internal testing, here is some additional feedback:

- A couple minor logic issues lead to inconsistency between block reward, budget value, and MN payment amount in terms of at which block they change.
- Suggest to include regtest in the rewards change process by transitioning away from the static 250 PIV block reward to the new block reward at the suggested changeover height (+1).
- During testing, after the new reward structure was activated, the GUI started labeling MN rewards as Budget payments, as the logic for that assumes any MN payment above `consensus.nMNBlockReward` must be a budget payment.

2022-08-04 00:51 UTC, tohsnoom commented on src/budget/budgetmanager.cpp
> +    if (nHeight < Params().GetConsensus().vUpgrades[Consensus::UPGRADE_V5_5].nActivationHeight) {
Made the correction.

2022-08-04 00:51 UTC, tohsnoom commented on src/validation.cpp
> +    if (nHeight >= Params().GetConsensus().vUpgrades[Consensus::UPGRADE_V5_5].nActivationHeight) {
Made the correction.

2022-08-04 00:53 UTC, tohsnoom commented on src/chainparams.cpp
> +        consensus.vUpgrades[Consensus::UPGRADE_V5_5].nActivationHeight          = 451;
Adjusted regtest activation to 576, and changed regtest reward schedule to change block reward at v5.5 activation.

2022-08-04 00:54 UTC, tohsnoom commented
I've added budget unit test cases for v5.5 activation.

2022-08-12 23:38 UTC, tohsnoom commented
Commits have been added for switching the protocol enforcement spork and adding a masternode payment amount unit test.

2022-09-11 05:48 UTC, Fuzzbawls approved these changes
ACK 7887920abaad3eb3140ae508adb274fcc38304c0

2022-09-15 19:26 UTC, DeanSparrow approved these changes
ACK 7887920abaad3eb3140ae508adb274fcc38304c0

I have reviewed these changes.

2022-09-17 02:02 UTC, yenachar commented
Downloaded, built (in release and debug), and reviewed the code without material issues.

2022-09-23 06:51 UTC, merged