[GUI] Fix ban actions in peer list
PIVX-Project/PIVX pull request #2852
Opened 2023-04-17 19:04 UTC by Liquid369

For quite some time in the PIVX GUI we have the old UX for the peer list, and it has not been functional to ban peers using the context menu. 
See below:
![Screenshot 2023-04-17 at 1 40 46 PM](https://user-images.githubusercontent.com/45834289/232580836-d0f39b6e-a258-4347-9245-afeaa197a3de.png)

Any amount of clicks, it will not ban said peer nor will it update the ban list. 

With this PR it is now working as intended again

![Screenshot 2023-04-17 at 1 42 12 PM](https://user-images.githubusercontent.com/45834289/232581174-007668e1-ce65-4ae8-a989-eb916b99b669.png)

Clicking ban node for X time, will automatically disconnect the peer and update the GUI/ban list

Changes:

We now track the nodes address in the NodeStats class, and so now we do not need to resolve the IP but rather pull it from the stats we have access to after syncing the information from the node.

2023-04-17 19:58 UTC, panleone requested changes
The ban button indeed does not work nice catch! Can you find a way to solve it without adding the CAddress as public field?

2023-04-17 20:03 UTC, Liquid369 commented
I will take a look, problem beforehand was resolving and looking it up 
I will play with it some tonight and tomorrow!

2023-04-18 19:26 UTC, Liquid369 commented
New way pushed, no longer tracking the address, but that itself is still tracked as addrName as a string, to which we can use for this instead.

2023-04-20 16:21 UTC, panleone submitted a review, later dismissed
tACK d33efa372b2e7148b2e0c3fe7a910e950ed5b1c7 working as expected

2023-05-02 06:32 UTC, Fuzzbawls requested changes
Functionally ACK, just need to clean up some minor clang-tidy issues.

2023-05-02 06:32 UTC, Fuzzbawls commented on src/qt/rpcconsole.cpp
> +    if(cachedNodeid == -1)
clang-tidy: missing whitespace after `if`
```diff
- if(cachedNodeid == -1)
+ if (cachedNodeid == -1)
```

2023-05-02 06:32 UTC, Fuzzbawls commented on src/qt/rpcconsole.cpp
> +    if(selectedNodeRow < 0)
clang-tidy: missing whitespace after `if`
```diff
- if(selectedNodeRow < 0)
+ if (selectedNodeRow < 0)
```

2023-05-02 06:32 UTC, Fuzzbawls commented on src/qt/rpcconsole.cpp
> +    const CNodeCombinedStats *stats = clientModel->getPeerTableModel()->getNodeStats(selectedNodeRow);
clang-tidy: Use `Left` Pointer Alignment
```diff
- const CNodeCombinedStats *stats = clientModel->getPeerTableModel()->getNodeStats(selectedNodeRow);
+ const CNodeCombinedStats* stats = clientModel->getPeerTableModel()->getNodeStats(selectedNodeRow);
```

2023-05-03 05:20 UTC, Fuzzbawls approved these changes
ACK a86ab9e0ce7b3911e59ebd24d31764e2a5be2d36

2023-05-03 09:04 UTC, merged