[Cleanup] Unify header guards
PIVX-Project/PIVX pull request #2936
Opened 2024-09-01 05:20 UTC by Fuzzbawls

For a while now, we've been using a mish-mash of various header guard styles, with no real consistency project wide. This PR remedies that by setting a strict header guard notation style.

All first-party headers now follow the below guard style:
```cpp
#ifndef PIVX_<PATH_TO>_<FILENAME>_H
#define PIVX_<PATH_TO>_<FILENAME>_H
...
#endif // PIVX_<PATH_TO>_<FILENAME>_H
```
Git subtrees and integrated 3rd party libraries are excluded.

A linter is included so as to prevent future inclusion of include guards that do not adhere to the above standard style.

With this in place, there is more opportunity to "declutter" our file structure quite a bit, **especially** with regards to the GUI files.

2024-09-17 06:53 UTC, panleone requested changes
only one small nit:

with the current script we check only that the header guard begins with  `PIVX_<PATH_TO>_<FILENAME>_H`

But something like
`PIVX_<PATH_TO>_<FILENAME>_H2323asd`

would be accepted too.

I suggested a small change to fix the issue

2024-09-17 06:53 UTC, panleone commented on test/lint/lint-include-guards.sh
> +    if [[ $(grep --count --extended-regexp "^#(ifndef|define|endif //) ${HEADER_ID}" "${HEADER_FILE}") != 3 ]]; then
```suggestion
    if [[ $(grep --count --extended-regexp "^#(ifndef|define|endif //) ${HEADER_ID}($|\s)" "${HEADER_FILE}") != 3 ]]; then
```

2024-09-18 12:42 UTC, Fuzzbawls commented on test/lint/lint-include-guards.sh
> +    if [[ $(grep --count --extended-regexp "^#(ifndef|define|endif //) ${HEADER_ID}" "${HEADER_FILE}") != 3 ]]; then
added

2024-10-22 08:11 UTC, panleone approved these changes
tACK 76b04cbfd8c4f7af7cbc46ce447e7d52a634649a

2024-10-23 12:23 UTC, Liquid369 approved these changes
tACK 76b04cbfd8c4f7af7cbc46ce447e7d52a634649a

2024-10-30 12:01 UTC, Duddino approved these changes
ACK 76b04cbfd8c4f7af7cbc46ce447e7d52a634649a

2024-10-31 01:41 UTC, merged